name: pdw-shop-backend
proxy:
  appserver:
    - pdw-shop-backend.lndo.site
services:
  database:
    type: postgres:13
    creds:
      user: postgres
      password: postgres
      database: database
  appserver:
    type: compose
    build:
      - chmod +x /app/docker/lando/java/cmd.sh
    scanner: false
    services:
      build: ./docker/lando/java
      command: /app/docker/lando/java/cmd.sh
      ports:
        - "8080:8080"
        - "5005:5005"
      environment:
        LANDO_DROP_USER: www-data
tooling:
  compile:
    service: appserver
    cmd: cd /app && ./gradlew build
  test:
    service: appserver
    cmd: cd /app && ./gradlew test
  postgresql:
    service: database
    cmd: psql -U postgres -d database
  spotless:
    service: appserver
    cmd: cd /app && ./gradlew spotlessJavaApply
  spotbugs:
    service: appserver
    cmd: cd /app && ./gradlew spotbugsMain && ./gradlew spotbugsTest
  hibernateSchema:
    service: appserver
    cmd: cd /app && ./gradlew -Dspring.profiles.active=generatesql bootRun
