name: pdw-shop-backend
proxy:
  appserver:
    - pdw-shop-backend.lndo.site
  mailhog:
    - pdw-shop-mailhog.lndo.site
services:
  database:
    type: postgres:13
    creds:
      user: postgres
      password: postgres
      database: database
  appserver:
    type: compose
    build:
      - apk update && apk upgrade && apk add bash
      - chmod +x /app/docker/lando/java/cmd.sh
    scanner: false
    services:
      image: adoptopenjdk/openjdk11:alpine
      command: /app/docker/lando/java/cmd.sh
      ports:
        - "8080:8080"
        - "5005:5005"
      expose:
        - "587" # for gmail mail sending
      environment:
        LANDO_DROP_USER: www-data
        STRIPE_API_KEY: "THE_API_KEY"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
tooling:
  compile:
    service: appserver
    cmd: cd /app && ./gradlew build
  test:
    service: appserver
    cmd: cd /app && ./gradlew test
  postgresql:
    service: database
    cmd: psql -U postgres -d database
  spotless:
    service: appserver
    cmd: cd /app && ./gradlew spotlessJavaApply
  spotbugs:
    service: appserver
    cmd: cd /app && ./gradlew spotbugsMain && ./gradlew spotbugsTest
  hibernateSchema:
    service: appserver
    cmd: cd /app && ./gradlew -Dspring.profiles.active=generatesql bootRun
