name: pdw-shop-backend
proxy:
  appserver:
    - pdw-shop-backend.lndo.site:8080
services:
  database:
    type: postgres:13
    creds:
      user: postgres
      password: postgres
      database: database
  appserver:
    type: compose
    build:
      - chmod +x /app/docker/lando/java/cmd.sh
    scanner: false
    services:
      build: ./docker/lando/java
      command: /app/docker/lando/java/cmd.sh
      ports:
        - "8080:8080"
        - "5005:5005"
      environment:
        LANDO_DROP_USER: www-data
        JDBC_DATABASE_URL: "jdbc:postgresql://database:5432/database"
        JDBC_DATABASE_USERNAME: postgres
        JDBC_DATABASE_PASSWORD: postgres
tooling:
  compile:
    service: appserver
    cmd: cd /app && ./gradlew build
  test:
    service: appserver
    cmd: cd /app && ./gradlew test
  mysql:
    service: database
    cmd: mysql -uroot