application:
  name: pdw-shop-backend
  project: pdw
  publicly_accessible: true
databases:
- type: mysql
  version: "8.0"
  name: my-db
routers:
  - name: main
    routes:
    - application_name: pdw-shop-backend
      paths:
      - /
