server:
  port: ${PORT:8080}
  session:
    tracking-modes: 'cookie'

spring:
  jackson:
    property-naming-strategy: "SNAKE_CASE"
    date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_empty
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://database:5432/database"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: sendmailhog
    port: 1025
    username:
    password:
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 1800000

---
spring:
  config:
    activate:
      on-profile: generatesql
  flyway:
    enabled: false
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: src/main/resources/ddl_jpa_creation.sql
