server:
  port: 8080

spring:
  jackson:
    property-naming-strategy: "SNAKE_CASE"
    date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_empty
  datasource:
    url: "jdbc:mysql://${QOVERY_DATABASE_MY_DB_HOST:127.0.0.1}:${QOVERY_DATABASE_MY_DB_PORT:3306}/${QOVERY_DATABASE_MY_DB_DATABASE:database}"
    username: ${QOVERY_DATABASE_MY_DB_USERNAME:mysql}
    password: ${QOVERY_DATABASE_MY_DB_PASSWORD:mysql}
  jpa:
    hibernate:
      # Don't do this at home...
      ddl-auto: update
# TODO: Flyway
