server:
  port: ${PORT:8080}

spring:
  jackson:
    property-naming-strategy: "SNAKE_CASE"
    date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_empty
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baselineOnMigrate: true
