insert into producer (name) values ('Evian');
insert into producer (name) values ('Apollinaris');
insert into producer (name) values ('Vilsa');
insert into producer (name) values ('Carolinen');
insert into producer (name) values ('Erdinger');
insert into producer (name) values ('Paulaner');
insert into producer (name) values ('Augustiner');
insert into producer (name) values ('Detmolder');
insert into producer (name) values ('Krombacher');
insert into producer (name) values ('Einbecker');
insert into producer (name) values ('Veltins');
insert into producer (name) values ('Grey Goose');
insert into producer (name) values ('Belvedere');
