FROM adoptopenjdk/openjdk11:alpine
MAINTAINER Romaric Philogène <rphilogene@qovery.com>

RUN apk update && apk upgrade && apk add bash

#RUN cd /usr/local/bin && wget https://services.gradle.org/distributions/gradle-7.1-all.zip && \
#/usr/bin/unzip gradle-7.1-all.zip && ln -s /usr/local/bin/gradle-7.1/bin/gradle /usr/bin/gradle

EXPOSE 8080
